[package]
name = "rustyfinance"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
csv = "1.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
